import { notFound } from 'next/navigation'
import Image from 'next/image'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'
import CommentSection from '@/components/CommentSection'
import { formatDate } from '@/utils'
import { Post } from '@/types'
 
interface Props { params: { id: string } }
 
export async function generateMetadata({ params }: Props) {
  const supabase = createClient()
  const { data } = await supabase.from('posts').select('title,summary').eq('id', params.id).single()
  if (!data) return { title: 'Post Not Found' }
  return { title: data.title, description: data.summary }
}
 
export default async function PostPage({ params }: Props) {
  const supabase = createClient()
 
  const { data: post } = await supabase
    .from('posts')
    .select('*, author:users(id,name,email,role), comments(*, user:users(id,name,email,role))')
    .eq('id', params.id)
    .single() as { data: Post | null }
 
  if (!post) notFound()
 
  return (
    <article className="max-w-3xl mx-auto px-4 py-12">
      {post.image_url && (
        <div className="relative h-72 w-full rounded-lg overflow-hidden mb-8 -mx-4 md:mx-0">
          <Image src={post.image_url} alt={post.title} fill className="object-cover" priority />
        </div>
      )}
 
      <header className="mb-8">
        <h1 className="font-display text-4xl md:text-5xl font-bold text-ink leading-tight mb-4">{post.title}</h1>
        <div className="flex items-center gap-4 text-sm text-ink/60 font-body">
          <span>By <span className="font-bold text-ink">{post.author?.name}</span></span>
          <span>·</span>
          <span>{formatDate(post.created_at)}</span>
          {post.updated_at !== post.created_at && (
            <><span>·</span><span>Updated {formatDate(post.updated_at)}</span></>
          )}
        </div>
      </header>
 
      {post.summary && (
        <div className="bg-paper-dark border-l-4 border-accent px-6 py-5 rounded-r-lg mb-8">
          <div className="flex items-center gap-2 mb-2">
            <span className="text-xs font-bold bg-accent text-paper px-2 py-0.5 rounded">✨ AI SUMMARY</span>
            <span className="text-xs text-ink/50">Generated by Google Gemini</span>
          </div>
          <p className="font-body text-ink/80 leading-relaxed text-sm">{post.summary}</p>
        </div>
      )}
 
      <div className="font-body text-ink/90 leading-loose text-lg whitespace-pre-wrap mb-12">
        {post.body}
      </div>
 
      <div className="pt-8 border-t-2 border-ink/10 mb-6">
        <Link href="/" className="text-sm text-accent font-bold hover:underline">← Back to all posts</Link>
      </div>
 
      <CommentSection
        postId={post.id}
        initialComments={(post.comments ?? []).sort(
          (a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
        )}
      />
    </article>
  )
}